- quartical/gains/general/generics.py
I whitespaced myself - this fixes a major regression I introduced when speeding up phase-only terms. This was missed by the tests as it only affects chains of terms. Simple fix.
> Fix error in amplocked residual.

- quartical/gains/amplitude/kernel.py
- quartical/gains/crosshand_phase/kernel.py
- quartical/gains/delay/kernel.py
- quartical/gains/phase/kernel.py
This PR includes some small optimizations for some of the solvers. Improvements range from 5% - 30%. Prelude to further attempts at row-parallel kernels.
> Optimize parameterized solvers

- quartical/calibration/solver.py
- quartical/gains/amplitude/kernel.py
- quartical/gains/complex/diag_kernel.py
- quartical/gains/complex/kernel.py
- quartical/gains/crosshand_phase/kernel.py
- quartical/gains/delay/kernel.py
- quartical/gains/general/convenience.py
- quartical/gains/general/generics.py
- quartical/gains/phase/kernel.py
- quartical/gains/rotation_measure/kernel.py
- quartical/gains/tec/kernel.py
This PR addresses a long-standing issue - what do we do when we have very large solution intervals? QuartiCal already has the ability to process solution intervals in parallel. However, the limiting case (which is not entirely unusual) of `(inf, inf)` solution intervals leaves us with no (easy) axis over which to do things in parallel.
I have attempted many different approaches (see branch name), all of which had a sharp edge such as performance degradation or increased memory footprint. The approach in this PR is the culmination of all those previous attempts and should allow for an arbitrary degree of internal parallelism with low to virtually non-existent memory and compute overheads.
For the sake of posterity, I will quickly detail the idea behind the approach (which is actually …
> Arbitrary internal parallelism

- quartical/interpolation/interpolate.py
Outdated use of `pathlib` was making it impossible to load from s3. This has been fixed.
> Support loading terms from s3.

- setup.py
We want to support s3 by default, so this should be installed by default.
> Add s3 to dask-ms dependency.

- quartical/config/external.py
Add check for user specifying scheduler address without setting dask scheduler to distributed.
> Warn on ambiguous dask input

- quartical/calibration/calibrate.py
- quartical/config/external.py
- quartical/config/helpstrings.yaml
- quartical/executor.py
- quartical/gains/datasets.py
- quartical/gains/general/generics.py
- testing/data/test_config.yaml
As per @landmanbester's request, this replaces `output.net_gain` with `output.net_gains`. This new option accepts a list of strings or a list of lists of strings. If the first case, all listed terms will be combined into a single effective gain at full time and frequency resolution. In the second case, each sub-list will be combined into a separate effective gain.
This may be clearer with an example. Let us assume we specified `solver.terms=[G,K,B,X,D]`. We could now use `output.net_gains` to do any of the following:
- `output.net_gains=[G,K,B,X,D]`: produce a single net/effective gain which includes all the terms. This is consistent with the old behaviour. Output will be named `GKBXD-merged`.
- `output.net_gains=[G,K,B]`: Combine a subset of terms into an effective gain. Output will be …
> Compose net gains from arbitrary terms.

- quartical/gains/general/generics.py
@landmanbester This should fix your error.
For posterity, this fixes a flaw in the code which resamples the solution intervals onto a finer grid to allow additional parallelism inside the solvers. Previously, I had only tested it on infinite solution intervals and not on normal solution intervals but on a very small data partition (e.g. a very short scan). This case revealed a minor flaw which was resulting in the remapping being constructed incorrectly. This has now been resolved.
> Fix prange work creation for large solution intervals/limited data.

- quartical/data_handling/ms_handler.py
> Make `write_xds_list` a no-op if no outputs are required

- quartical/config/external.py
- quartical/config/helper.py
- quartical/config/helpstrings.yaml
- quartical/config/internal.py
- quartical/flagging/flagging.py
- quartical/flagging/flagging_kernels.py
The MAD flagging code was some of my first dask code. As such, it was very messy and probably slightly incorrect. This is not a complete fix - that will require a full rewrite - but this should improve its behaviour/make it more correct. At present I am using the whitened residuals (`np.sqrt(r*r.conj()*W)`) in the MAD flagger but it is possible the `np.sqrt` can be omitted. It is now possible to disable whitening (the multiplication by W in the above expression) for cases where the weights are known to be incorrect. 
@landmanbester feel free to give it a test drive.
> Improve MAD code

- quartical/calibration/mapping.py
Fix regression introduced when adding a default SCAN_NUMBER column. Fixes associated memory footprint growth and broken logging.
> Fix for memory footprint regression when using LocalCluster

- quartical/config/external.py
- quartical/data_handling/model_handler.py
- quartical/data_handling/ms_handler.py
Only support P jones application when four correlations are present. Fixes #215.
> Disable P jones settings by default.

- quartical/flagging/flagging_kernels.py
This should address a bug exposed by @o-smirnov when using both a UV-cut and the MAD flags. The combination of these two parameters results in the temporary flags used to implement the UV-cut being turned into permanent flags. I am just testing this on the original reproducer and will merge once the tests pass/that example runs correctly.
> Ignore temporary flags in MAD code.

- quartical/data_handling/ms_handler.py
This should fix #226 as reported by @bennahugo. The problem was originally caused by relying on `xds_from_storage_ms` to produce a complete list of column names. This is unreliable as columns can be omitted if they have an invalid exemplar row (@bennahugo's case). This PR removes the problematic assert and replaces it with a `try except` which relies on the underlying daskms routines to raise sensible error messages which we can augment for readability.
> Change approach for identifying missing columns.

- quartical/config/external.py
- quartical/config/helpstrings.yaml
- quartical/config/preprocess.py
- quartical/data_handling/model_handler.py
- quartical/executor.py
- quartical/utils/array.py
Fixes #222 (adds). `input_model.recipe` will no longer be a mandatory argument. Instead, if left unspecified it will default to an identity model. A warning will be logged to protect users who end up in this situation inadvertently.
> Add support for identity model.

- quartical/config/external.py
- quartical/gains/__init__.py
- quartical/gains/leakage/__init__.py
- quartical/gains/leakage/kernel.py
In preparation for further polcal experiments, it is useful to have an explicit leakage term. Practically, this just a complex 2x2 term which discards its on-diagonal updates. This is important as otherwise the leakage term will absorb errors which should instead be in the time-dependent gain/bandpass. This should also make plotting the leakages simpler as they are simply the off-diagonal terms of the D matrix. 
Edit: Note that no additional tests have been added as this terms is functionally identical to a 2x2 complex term and is therefore tested implicitly.
> Add proper leakage term (unity diagonal).

- quartical/config/external.py
- quartical/interpolation/interpolate.py
@landmanbester Hopefully does what it says - this was a simple enough hack. If `term.interp_mode` is set to `amp`, the interpolated gains will have zero phase. If `term.interp_mode` is set to `phase`, the interpolated gains will have unity amplitude. Note that these modes are only suitable for diagonal terms.
> Add support for interpolation in only amp or phase i.e. ignore the non-interpolated part.

- quartical/config/external.py
- quartical/gains/__init__.py
- quartical/gains/delay/__init__.py
- quartical/gains/delay/pure_kernel.py
@landmanbester As it says on the label. Set `term.type=pure_delay`. I do not love this naming convention but will wait till a later release to replace it with something more explicit as I do not want to change the existing behaviour of `term.type=delay`. At present this will be no faster than a `delay` term as I am simply discarding the offsets on each iteration. Ultimately it may be worth writing a special code path which does less work but I don't think it is a priority.
> Add a pure delay solver (no offset).

- quartical/calibration/constructor.py
- quartical/gains/delay/kernel.py
- quartical/gains/delay/pure_kernel.py
- quartical/gains/tec/kernel.py
This functionality had been added and seems to work. One known issue is the scaling of certain values. Due to the scaling of values like the channel frequencies, the entries of jhj will also end up being scaled. I am yet to figure out the correct way of unscaling jhj values.
> Write out diagonal entries of jhj matrix when solving parameterized terms.

- quartical/calibration/calibrate.py
- quartical/data_handling/angles.py
- quartical/flagging/flagging_kernels.py
- quartical/gains/amplitude/kernel.py
- quartical/gains/baseline.py
- quartical/gains/complex/diag_kernel.py
- quartical/gains/complex/kernel.py
- quartical/gains/crosshand_phase/kernel.py
- quartical/gains/datasets.py
- quartical/gains/delay/kernel.py
- quartical/gains/delay/pure_kernel.py
- quartical/gains/general/convenience.py
- quartical/gains/general/factories.py
- quartical/gains/general/flagging.py
- quartical/gains/general/generics.py
- quartical/gains/leakage/kernel.py
- quartical/gains/phase/kernel.py
- quartical/gains/rotation/kernel.py
- quartical/gains/rotation_measure/kernel.py
- quartical/gains/tec/kernel.py
- quartical/interpolation/interpolants.py
- quartical/statistics/stat_kernels.py
- quartical/utils/intervals.py
- quartical/utils/maths.py
- quartical/utils/numba.py
- quartical/weights/robust.py
- testing/utils/gains.py
This is still in a WIP but I wanted to get the tests firing off as I change things - I have already made changes to a large amount of the code but some modules still need to be migrated. `@overload` is pretty much a drop in replacement in most cases. The awkward case is functions which were previously wrapped with `@generated_jit` and are called from Python. An overload only works when the called from a jitted function. This means that you can end up with the following:
```python
from numba import njit
from numba.extending import overload
@njit
def f(*args):  # Can be called from Python.
return f_impl(*args)
def f_impl(*args):
raise NotImplementedError
@overload(f_impl)
def nb_f_impl(*args):
def impl(*args):
return len(args)
return impl
f(1, 2, 3)  # Will work.
f_impl(1, 2, 3)  # Raises …
```
> Replace all instances of `generated_jit` with `overload`.

- quartical/flagging/flagging.py
- quartical/interpolation/interpolants.py
While running the test suite, I noticed that a huge number of warnings were being generated. These were related to a `numpy` indexing quirk exposed by `dask` and the pending deprecation of `interp2d` in `scipy`. This PR fixes these issues, massively reducing the spurious warnings. Some warnings remain but they are all upstream and have been reported on the various repositories.
> Fix multiple sources of warnings 

- quartical/calibration/solver.py
- quartical/config/argument_schema.yaml
- quartical/gains/complex/diag_kernel.py
- quartical/gains/delay/kernel.py
- quartical/gains/delay/pure_kernel.py
- quartical/gains/phase/kernel.py
- quartical/gains/tec/kernel.py
Should do what it says on the label. For now, the implementation assumes that the reference antenna is always present. Dealing with a heavily flagged reference antenna is challenging and I haven't thought of an adequate solution yet.
This will guarantee zero phase on the reference antenna which is important for X/D calibration.
> Add antenna referencing to diagonal terms

- pyproject.toml
- quartical/interpolation/interpolants.py
- tbump.toml
Fixes #251. The issue stems from the fact that users may interpolate to points far outside the domain of the existing solutions. Linear extrapolation is really bad in this context so we now use a hybrid approach - linear interpolation in the domain and nearest neighbour interpolation/extrapolation outside the domain. This should be approximately safe. 
A few more experiments are required to validate the new behaviour in the presence of heavily flagged data.
> Use nearest-neighbour interpolation in regions where extrapolation is required.

- quartical/apps/backup.py
This is a partial fix for https://github.com/ratt-ru/QuartiCal/issues/297. The remaining cases that are not catered for are:
* restoring to a non-existent column (i.e. create a new column)
* I believe there may also still be an issue when trying to restore to a non-standard column in an MS as it needs a a schema.
I believe these are both fairly exotic use cases but let me know if you want me to look into that @JSKenyon
> Don't allow restore app to overwrite metadata

- pyproject.toml
- quartical/apps/summary.py
- quartical/calibration/calibrate.py
- quartical/calibration/constructor.py
- quartical/calibration/mapping.py
- quartical/data_handling/angles.py
- quartical/data_handling/bda.py
- quartical/data_handling/model_handler.py
- quartical/data_handling/ms_handler.py
- quartical/flagging/flagging.py
- quartical/gains/baseline.py
- quartical/gains/datasets.py
- quartical/interpolation/interpolants.py
- quartical/interpolation/interpolate.py
- quartical/statistics/logging.py
- tbump.toml
- testing/tests/calibration/test_calibrate.py
- testing/tests/gains/test_amplitude.py
- testing/tests/gains/test_complex.py
- testing/tests/gains/test_crosshand_phase.py
- testing/tests/gains/test_delay.py
- testing/tests/gains/test_delay_and_offset.py
- testing/tests/gains/test_diag_complex.py
- testing/tests/gains/test_phase.py
- testing/tests/gains/test_rotation.py
- testing/tests/gains/test_rotation_measure.py
- testing/tests/gains/test_tec_and_offset.py
xarray will be changing the return type of `xds.dims` to a set (it is currently a dict). This was generating a huge number of pending deprection warnings. This PR should replace all the required instances of `xds.dims` with `xds.sizes`.
> Fix xarray dims

- quartical/scheduling/__init__.py
Dask has removed the `graph_metrics` function. This breaks the scheduler plugin. I have copied the function in question into QaurtiCal's source - it has no dask dependencies.
> Move graph metrics function into the scheduler plugin code.

- quartical/scheduling/__init__.py
Dask has reverted to tuple keys (from string) - see #315. This workaround restringifies the keys in the scheduler plugin to avoid errors. This is a temporary solution, but it should be adequate until I have a chance to rewrite/improve the plugin.
> Restringify keys in scheduler plugin.

- quartical/config/gain_schema.yaml
- quartical/gains/__init__.py
- quartical/gains/delay_and_tec/__init__.py
- quartical/gains/delay_and_tec/kernel.py
- testing/tests/gains/test_delay_and_tec.py
@rcyndie This PR adds a new term type called `delay_and_tec` which includes both effects (but not a global phase offset). It should be very familiar to you, and I have left the existing delay estimate code as is. You can pull these changes to your local branch and work on integrating the combined initial estimates. Note that you should now be able to solve after estimating, and that the `params_to_gains` function should already be correct. The parameters are laid out as `[tec_XX, delay_XX, tec_YY, delay_YY]`.
> Add experimental combined delay and tec solver.

- quartical/config/argument_schema.yaml
Does what it says on the label. Currently URIs are not supported in the interpolation code as stimela doesn't appear happy with `Optional[URI]`.
> Make schema consistent with that required by cult-cargo.

- quartical/data_handling/angles.py
This should help resolve the failing @landmanbester's failing kubernetes case - the problem was caused by QuartiCal incorrectly assuming a uniform feed subtable. This was inconsistent with the behaviour in `dask-ms convert`.
> Do not assume that the FEED subtable is uniform

- quartical/data_handling/angles.py
(Partially) fixes the issue with reading the FEED subtable.
> Changes for minor release

- quartical/calibration/solver.py
- quartical/config/gain_schema.yaml
- quartical/gains/__init__.py
- quartical/gains/feed_flip/__init__.py
Finally caving to @o-smirnov and @bennahugo's requests. This adds an explicit feed flip term. This can be included in your `solver.terms` by selecting type `feed_flip`. Note that if you require parallactic angle correction, you should use the newly added explicit `parallactic_angle` term and not the `input_model.apply_p_jones` and `output.apply_p_jones_inv` options. The current approach will up computational complexity - I will work on improving this but it will be a big job as I will need to refactor how the gains are collapsed within the chain. That will likely be a separate future PR. 
Currently unanswered questions:
- Are the weights also flipped?
- Is simply including the flip in the chain sufficient to address the problem?
> Add feed flip term.

- quartical/calibration/solver.py
- quartical/config/gain_schema.yaml
- quartical/gains/amplitude/kernel.py
- quartical/gains/complex/diag_kernel.py
- quartical/gains/complex/kernel.py
- quartical/gains/crosshand_phase/kernel.py
- quartical/gains/crosshand_phase/null_v_kernel.py
- quartical/gains/delay/kernel.py
- quartical/gains/delay_and_offset/kernel.py
- quartical/gains/delay_and_tec/kernel.py
- quartical/gains/gain.py
- quartical/gains/general/generics.py
- quartical/gains/leakage/kernel.py
- quartical/gains/phase/kernel.py
- quartical/gains/rotation/kernel.py
- quartical/gains/rotation_measure/kernel.py
- quartical/gains/tec_and_offset/kernel.py
- testing/fixtures/gains.py
- testing/tests/gains/test_amplitude.py
- testing/tests/gains/test_delay_and_offset.py
- testing/tests/gains/test_diag_complex.py
- testing/tests/gains/test_phase.py
As requested by @o-smirnov in #357. This is a slightly more general offering; diagonal parameterised Jones terms now support a support a scalar mode where appropriate. This is enabled by setting `term.scalar=true` where `term` is the name of any specified gain term.
At present, the scalar mode is not supported for `diag_complex` terms. This is because the solver is a little different for the diagonal complex case and the generic approach I have taken in this PR won't work.  
Edit: I have added support for scalar `diag_complex` terms.
> Add a scalar mode to diagonal parameterised Jones terms

- quartical/data_handling/angles.py
- quartical/data_handling/ms_handler.py
Fixes #226 and is related to #363. At present, due to the manner in which datasets are opened with `xds_from_table` and its variants, the code was checking for the presence of columns on deselected datasets. This PR is the simple solution, but a more comprehensive refactoring is required.
> Add a workaround for selection in the presence of partial columns

- quartical/calibration/constructor.py
- quartical/data_handling/ms_handler.py
- quartical/gains/delay/__init__.py
- quartical/gains/delay/kernel.py
- quartical/gains/delay_and_offset/__init__.py
- quartical/gains/delay_and_offset/kernel.py
- quartical/gains/delay_and_tec/__init__.py
- quartical/gains/delay_and_tec/kernel.py
- quartical/gains/tec_and_offset/__init__.py
- quartical/gains/tec_and_offset/kernel.py
This PR is the first step in correcting for a subtle error discussed in #366. This does not fix the (unusual) case where multiple delay/TEC terms are solved along the frequency axis. Instead, this resolves the more common problem which was occurring when loading a delay/TEC term from disk with different chunking. This resulted in a change in the minimum and maximum frequencies in each chunk which in turn altered the parameterisation. All the delay/TEC terms now use the global minimum and maximum frequencies (in each SPW) in their parameterisation to avoid this problem.
> Update delay/TEC parameterisation to use global frequency information
